# Site settings
title: John Doe
email: john@example.com
description: >
  Personal portfolio of John Doe showcasing projects and blog posts.
baseurl: ""
url: ""

# Social usernames
github_username: johndoe
twitter_username: johndoe
linkedin_username: johndoe

# Build settings
markdown: kramdown
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Google Analytics (placeholder ID)
google_analytics: UA-XXXXXXX-X
